import React, { useEffect, useState } from 'react';
import MapComponent from './components/MapComponent';
import Sidebar from './components/Sidebar';
import Backoffice from './components/Backoffice';
import LoginModal from './components/LoginModal';
import { Poi, RouteInfo } from './types';
import { getRouteDescription } from './services/geminiService';
import { supabase } from './services/supabaseClient';

const DEFAULT_ROUTE_INFO: RouteInfo = {
  distance: "16 km",
  duration: "1h10",
  difficulty: "Facile",
  description: "Une étape agréable mêlant patrimoine historique avec le château de Selles-sur-Cher et douceur de vivre le long du Canal de Berry.",
  partnerLogos: []
};

// Helper to convert DB snake_case to CamelCase
const mapDbPoiToAppPoi = (dbPoi: any): Poi => ({
  id: dbPoi.id,
  name: dbPoi.name,
  type: dbPoi.type,
  description: dbPoi.description || '',
  position: dbPoi.position, // JSONB stored as object
  imageUrl: dbPoi.image_url,
  phone: dbPoi.phone,
  website: dbPoi.website,
  openingHours: dbPoi.opening_hours,
  address: dbPoi.address,
  zipCode: dbPoi.zip_code,
  city: dbPoi.city
});

// Helper to convert App POI to DB snake_case
const mapAppPoiToDbPoi = (poi: Poi) => ({
  // id is handled by DB for new items, or used for updates
  name: poi.name,
  type: poi.type,
  description: poi.description,
  position: poi.position,
  image_url: poi.imageUrl,
  phone: poi.phone,
  website: poi.website,
  opening_hours: poi.openingHours,
  address: poi.address,
  zip_code: poi.zipCode,
  city: poi.city
});

export default function App() {
  const [pois, setPois] = useState<Poi[]>([]);
  const [selectedPoi, setSelectedPoi] = useState<Poi | null>(null);
  const [routeInfo, setRouteInfo] = useState<RouteInfo | null>(null);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isLoading, setIsLoading] = useState(true);
  
  // Auth & Admin States
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [showLogin, setShowLogin] = useState(false);
  const [showBackoffice, setShowBackoffice] = useState(false);

  // Initial Data Load
  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        // 1. Fetch POIs
        const { data: poiData, error: poiError } = await supabase
          .from('pois')
          .select('*');
        
        if (poiError) throw poiError;

        if (poiData && poiData.length > 0) {
          setPois(poiData.map(mapDbPoiToAppPoi));
        } else {
          // Fallback if DB is empty? Or just empty list.
          // Optional: Load defaults if DB is strictly empty to seed it (manual action preferred)
          setPois([]); 
        }

        // 2. Fetch Route Info
        const { data: routeData, error: routeError } = await supabase
          .from('route_info')
          .select('*')
          .single(); // Assuming single row

        if (routeData) {
          setRouteInfo({
            distance: routeData.distance,
            duration: routeData.duration,
            difficulty: routeData.difficulty,
            description: routeData.description,
            partnerLogos: routeData.partner_logos || []
          });
        } else {
           // Fallback / AI Generation
           const info = await getRouteDescription('Châtillon-sur-Cher', 'Gièvres');
           setRouteInfo(info);
        }

      } catch (err) {
        console.error('Error fetching data from Supabase:', err);
        // Fallback to defaults in case of connection error
        setRouteInfo(DEFAULT_ROUTE_INFO);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();

    // Check existing auth session
    const auth = sessionStorage.getItem('admin-auth');
    if (auth === 'true') setIsAuthenticated(true);

    if (window.innerWidth < 768) {
      setIsSidebarOpen(false);
    }
  }, []);

  const handlePoiSelect = (poi: Poi) => {
    setSelectedPoi(poi);
    setIsSidebarOpen(true);
  };

  const handleSavePoi = async (newPoi: Poi) => {
    // Optimistic Update
    const isUpdate = !!pois.find(p => p.id === newPoi.id);
    
    // DB Update
    const dbPayload = mapAppPoiToDbPoi(newPoi);
    
    if (isUpdate) {
       const { error } = await supabase
         .from('pois')
         .update(dbPayload)
         .eq('id', newPoi.id);
       
       if (error) {
         console.error('Error updating POI:', error);
         alert("Erreur lors de la mise à jour");
         return;
       }

       setPois(prev => prev.map(p => p.id === newPoi.id ? newPoi : p));
    } else {
       // Insert (let DB generate ID)
       // We need to remove the temporary ID if it was generated by frontend, 
       // but typically we pass 'id' undefined for insert, or handle returning.
       const { data, error } = await supabase
         .from('pois')
         .insert(dbPayload)
         .select()
         .single();
       
       if (error || !data) {
         console.error('Error inserting POI:', error);
         alert("Erreur lors de la création");
         return;
       }
       
       const createdPoi = mapDbPoiToAppPoi(data);
       setPois(prev => [...prev, createdPoi]);
       // If we were editing a temp ID, we might need to close/reopen, but usually fine
    }

    if (selectedPoi && selectedPoi.id === newPoi.id) {
      setSelectedPoi(newPoi);
    }
  };

  const handleDeletePoi = async (id: string) => {
    if (!confirm('Êtes-vous sûr de vouloir supprimer ce point ?')) return;

    const { error } = await supabase
      .from('pois')
      .delete()
      .eq('id', id);

    if (error) {
      console.error('Error deleting POI:', error);
      alert("Erreur lors de la suppression");
      return;
    }

    setPois(prev => prev.filter(p => p.id !== id));
    if (selectedPoi && selectedPoi.id === id) {
      setSelectedPoi(null);
    }
  };

  const handleUpdateRouteInfo = async (info: RouteInfo) => {
    // We assume there's only one row in route_info or we insert one if missing
    // First, try to update existing
    const { data: existing } = await supabase.from('route_info').select('id').single();

    const payload = {
      distance: info.distance,
      duration: info.duration,
      difficulty: info.difficulty,
      description: info.description,
      partner_logos: info.partnerLogos
    };

    if (existing) {
      await supabase.from('route_info').update(payload).eq('id', existing.id);
    } else {
      await supabase.from('route_info').insert(payload);
    }
    
    setRouteInfo(info);
  };

  const handleAdminClick = () => {
    if (isAuthenticated) {
      setShowBackoffice(true);
    } else {
      setShowLogin(true);
    }
  };

  const handleLoginSuccess = (success: boolean) => {
    if (success) {
      setIsAuthenticated(true);
      sessionStorage.setItem('admin-auth', 'true');
      setShowLogin(false);
      setShowBackoffice(true);
    }
  };

  return (
    <div className="flex h-screen w-screen overflow-hidden bg-gray-100 font-sans relative">
      
      {/* Loading Overlay */}
      {isLoading && (
        <div className="fixed inset-0 z-[2000] bg-white flex items-center justify-center">
          <div className="flex flex-col items-center">
            <div className="w-10 h-10 border-4 border-emerald-600 border-t-transparent rounded-full animate-spin mb-4"></div>
            <p className="text-gray-600 font-medium">Chargement des données...</p>
          </div>
        </div>
      )}

      {/* Backoffice Button */}
      <button 
        onClick={handleAdminClick}
        className="fixed bottom-4 right-4 z-[900] bg-slate-800 text-white p-3 rounded-full shadow-lg hover:bg-slate-700 transition-transform hover:scale-105"
        title="Administration"
      >
        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      </button>

      {/* Login Modal */}
      {showLogin && (
        <LoginModal 
          onLogin={handleLoginSuccess} 
          onClose={() => setShowLogin(false)} 
        />
      )}

      {/* Backoffice Modal */}
      {showBackoffice && isAuthenticated && (
        <Backoffice 
          pois={pois}
          routeInfo={routeInfo}
          onSavePoi={handleSavePoi}
          onDeletePoi={handleDeletePoi}
          onUpdateRouteInfo={handleUpdateRouteInfo}
          onClose={() => setShowBackoffice(false)}
        />
      )}

      {/* Mobile Toggle Button */}
      <button 
        className={`md:hidden absolute top-4 left-4 z-[500] bg-white p-2 rounded shadow text-emerald-700 ${isSidebarOpen ? 'hidden' : 'block'} hover:bg-gray-50 transition-colors`}
        onClick={() => setIsSidebarOpen(true)}
      >
        <span className="sr-only">Ouvrir le menu</span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
          <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>

      {/* Sidebar Container */}
      <div className={`
        fixed inset-y-0 left-0 transform transition-transform duration-300 ease-in-out z-[1000]
        md:relative md:translate-x-0 w-full md:w-auto
        ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}
        shadow-2xl md:shadow-none
      `}>
        <Sidebar 
          routeInfo={routeInfo} 
          selectedPoi={selectedPoi}
          onClosePoi={() => setSelectedPoi(null)}
          onUpdatePoi={handleSavePoi}
        />
        
        <button 
          onClick={() => setIsSidebarOpen(false)}
          className="md:hidden absolute top-3 right-3 p-2 bg-white/80 rounded-full text-gray-600 hover:text-gray-900 shadow-sm"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      {/* Main Map Area */}
      <div className="flex-1 h-full relative bg-gray-200">
        <MapComponent 
          pois={pois} 
          onSelectPoi={handlePoiSelect} 
        />
      </div>
    </div>
  );
}